import { Activity, ArrowUpRight, Clock3, Gauge, KeyRound, Radio, Server, ShieldCheck, Zap } from "lucide-react";
import { AppLayout } from "./_shared/AppLayout";
import { Metric, StatusPill, TinyBar, panel, muted } from "./_shared/EnginePrimitives";

const lanes = [
  ["AK-01 · •••• 91d2", "Healthy", 84, "42.6k / 100k"], ["AK-02 · •••• 08af", "Healthy", 61, "31.2k / 100k"], ["AK-03 · •••• f7c1", "Cooling", 27, "18.4k / 100k"], ["AK-04 · •••• 4be8", "Healthy", 76, "56.8k / 100k"], ["AK-05 · •••• b340", "Healthy", 49, "22.1k / 100k"], ["AK-06 · •••• 81aa", "Dead", 0, "0 / 100k"],
];
const activity = [["14:32:08", "Chapter 04", "Hindi retell completed", "green"], ["14:31:44", "Key AK-03", "Cooling · 41s remaining", "amber"], ["14:30:16", "Chapter 07", "Voice render started", "gold"], ["14:28:59", "Key AK-06", "429 rate limit isolated", "red"], ["14:27:20", "Chapter 02", "Audio stitched · 18.4 MB", "green"]];

export function EngineOverview() {
  return <AppLayout active="Settings" eyebrow="Audiobook AI · engine room" title="Engine overview" subtitle="A quiet control surface for the work behind every Hindi and Hinglish chapter. Watch capacity, health, and live work without guessing.">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#41353b] pb-5"><div className="flex items-center gap-2 text-[10px] text-[#a99790]"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#83a88c] opacity-60" /><span className="relative h-2 w-2 rounded-full bg-[#83a88c]" /></span> Pulse live · sampled 14:32:11 IST</div><button type="button" className="flex items-center gap-2 rounded-lg border border-[#58464a] px-3 py-2 text-[10px] font-bold text-[#d5ad80] hover:border-[#a87356]"><Activity size={13} /> Refresh snapshot</button></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="API key pool" value="12" detail="8 healthy · 2 cooling · 1 dead · 1 disabled" icon={<KeyRound size={14} className="text-[#d2a16f]" />} /><Metric label="Requests / min" value="184" detail="+12.4% from the last hour" icon={<Gauge size={14} className="text-[#d2a16f]" />} /><Metric label="Tokens / min" value="71.8k" detail="38.2k headroom across lanes" icon={<Zap size={14} className="text-[#d2a16f]" />} /><Metric label="Active jobs" value="4" detail="2 translating · 1 voice · 1 stitching" icon={<Radio size={14} className="text-[#8eae92]" />} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className={`${panel} p-5`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#c3946c]"><Server size={14} /> Independent quota lanes</div><h2 className="mt-2 font-serif text-[26px] text-[#eed9c4]">12 keys, one resilient queue</h2></div><StatusPill state="Healthy" /></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{lanes.map(([name, state, value, daily]) => <div key={name} className="rounded-xl border border-[#47383d] bg-[#352c31] p-3"><div className="flex items-center justify-between gap-2"><span className="font-mono text-[10px] text-[#d7c1b3]">{name}</span><span className={`text-[9px] font-bold uppercase ${state === "Dead" ? "text-[#cb8174]" : state === "Cooling" ? "text-[#d7ac72]" : "text-[#8eae92]"}`}>{state}</span></div><div className="mt-3 flex justify-between text-[9px] uppercase tracking-wider text-[#857578]"><span>TPM available</span><span className="font-mono text-[#cba476]">{value}%</span></div><div className="mt-1"><TinyBar value={Number(value)} tone={state === "Dead" ? "red" : state === "Healthy" ? "green" : "gold"} /></div><div className="mt-2 flex justify-between text-[9px] text-[#968580]"><span>Daily tokens</span><span className="font-mono">{daily}</span></div></div>)}</div><div className="mt-4 flex items-start gap-2 rounded-xl border border-[#52614e] bg-[#303a32] p-3 text-[10px] leading-relaxed text-[#a8baaa]"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[#8eae92]" />Failure isolation is on. Cooling or dead lanes are removed from rotation; completed chapters remain safe.</div></section>
      <section className={`${panel} p-5`}><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#c3946c]">Quota matrix</div><h2 className="mt-2 font-serif text-[25px] text-[#eed9c4]">Today&apos;s room</h2></div><ArrowUpRight size={16} className="text-[#d2a16f]" /></div><div className="mt-5 space-y-4">{[["Requests", 46, "4,612 / 10,000"], ["Input tokens", 64, "412k / 640k"], ["Output tokens", 38, "98k / 256k"], ["Audio minutes", 29, "74 / 256"]].map(([label, value, detail]) => <div key={label}><div className="flex justify-between text-[10px] text-[#a99790]"><span>{label}</span><span className="font-mono text-[#d4aa7a]">{detail}</span></div><div className="mt-2"><TinyBar value={Number(value)} tone={Number(value) > 70 ? "gold" : "green"} /></div></div>)}</div><div className="mt-6 border-t border-[#493a3f] pt-4 text-[10px] text-[#a08d88]"><span className="font-mono text-[#d6ad7b]">05h 28m</span> until daily reset · last checked 14:32</div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className={`${panel} p-5`}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#c3946c]"><Gauge size={14} /> Health distribution</div><div className="mt-5 flex items-center gap-5"><div className="relative flex h-28 w-28 items-center justify-center rounded-full border-[10px] border-[#3f343a]"><div className="absolute inset-[-10px] rounded-full border-[10px] border-transparent border-l-[#7ea286] border-t-[#7ea286] border-r-[#d4a36b] -rotate-12" /><div className="text-center"><strong className="block font-serif text-2xl text-[#f0d9c1]">8/12</strong><span className="text-[9px] uppercase tracking-wider text-[#968580]">healthy</span></div></div><div className="space-y-2 text-[10px]">{[["Healthy", "8", "bg-[#7ea286]"], ["Cooling", "2", "bg-[#d4a36b]"], ["Dead", "1", "bg-[#bd7668]"], ["Disabled", "1", "bg-[#71666a]"]].map(([label, count, color]) => <div key={label} className="flex items-center gap-2 text-[#a99790]"><span className={`h-2 w-2 rounded-full ${color}`} />{label}<span className="ml-auto font-mono text-[#e0c6ad]">{count}</span></div>)}</div></div></section><section className={`${panel} p-5`}><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#c3946c]"><Clock3 size={14} /> Live activity</div><h2 className="mt-2 font-serif text-[25px] text-[#eed9c4]">The engine is moving</h2></div><span className="text-[9px] text-[#8ea991]">updating</span></div><div className="mt-4 divide-y divide-[#45363c]">{activity.map(([time, subject, message, tone]) => <div key={time} className="flex items-center gap-3 py-2.5 text-[10px]"><span className="w-16 font-mono text-[#7f706f]">{time}</span><span className={`h-1.5 w-1.5 rounded-full ${tone === "green" ? "bg-[#7ea286]" : tone === "red" ? "bg-[#bd7668]" : tone === "amber" ? "bg-[#d4a36b]" : "bg-[#d89c61]"}`} /><strong className="text-[#d7c3b5]">{subject}</strong><span className="truncate text-[#9e8b87]">{message}</span></div>)}</div></section></div>
  </AppLayout>;
}