// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/audiobook-ai/AudioVersions.tsx": () => import("../components/mockups/audiobook-ai/AudioVersions.tsx"),
  "./components/mockups/audiobook-ai/AudiobookOverview.tsx": () => import("../components/mockups/audiobook-ai/AudiobookOverview.tsx"),
  "./components/mockups/audiobook-ai/AudiobookWorkspace.tsx": () => import("../components/mockups/audiobook-ai/AudiobookWorkspace.tsx"),
  "./components/mockups/audiobook-ai/BookOverview.tsx": () => import("../components/mockups/audiobook-ai/BookOverview.tsx"),
  "./components/mockups/audiobook-ai/Bookmarks.tsx": () => import("../components/mockups/audiobook-ai/Bookmarks.tsx"),
  "./components/mockups/audiobook-ai/ChapterAssets.tsx": () => import("../components/mockups/audiobook-ai/ChapterAssets.tsx"),
  "./components/mockups/audiobook-ai/ChapterNavigator.tsx": () => import("../components/mockups/audiobook-ai/ChapterNavigator.tsx"),
  "./components/mockups/audiobook-ai/CreateAudiobook.tsx": () => import("../components/mockups/audiobook-ai/CreateAudiobook.tsx"),
  "./components/mockups/audiobook-ai/EngineOverview.tsx": () => import("../components/mockups/audiobook-ai/EngineOverview.tsx"),
  "./components/mockups/audiobook-ai/GenerationOutcome.tsx": () => import("../components/mockups/audiobook-ai/GenerationOutcome.tsx"),
  "./components/mockups/audiobook-ai/GenerationQueue.tsx": () => import("../components/mockups/audiobook-ai/GenerationQueue.tsx"),
  "./components/mockups/audiobook-ai/Home.tsx": () => import("../components/mockups/audiobook-ai/Home.tsx"),
  "./components/mockups/audiobook-ai/KeyPool.tsx": () => import("../components/mockups/audiobook-ai/KeyPool.tsx"),
  "./components/mockups/audiobook-ai/Library.tsx": () => import("../components/mockups/audiobook-ai/Library.tsx"),
  "./components/mockups/audiobook-ai/ListeningMode.tsx": () => import("../components/mockups/audiobook-ai/ListeningMode.tsx"),
  "./components/mockups/audiobook-ai/Maintenance.tsx": () => import("../components/mockups/audiobook-ai/Maintenance.tsx"),
  "./components/mockups/audiobook-ai/MiniPlayer.tsx": () => import("../components/mockups/audiobook-ai/MiniPlayer.tsx"),
  "./components/mockups/audiobook-ai/Notes.tsx": () => import("../components/mockups/audiobook-ai/Notes.tsx"),
  "./components/mockups/audiobook-ai/ReaderProvenance.tsx": () => import("../components/mockups/audiobook-ai/ReaderProvenance.tsx"),
  "./components/mockups/audiobook-ai/RetellingPreview.tsx": () => import("../components/mockups/audiobook-ai/RetellingPreview.tsx"),
  "./components/mockups/audiobook-ai/Settings.tsx": () => import("../components/mockups/audiobook-ai/Settings.tsx"),
  "./components/mockups/audiobook-ai/TranslationPipeline.tsx": () => import("../components/mockups/audiobook-ai/TranslationPipeline.tsx"),
  "./components/mockups/audiobook-ai/VoiceStudio.tsx": () => import("../components/mockups/audiobook-ai/VoiceStudio.tsx"),
  "./components/mockups/templates/MissionControlBentoDashboard-y0LfqW/Dashboard.tsx": () => import("../components/mockups/templates/MissionControlBentoDashboard-y0LfqW/Dashboard.tsx")
};
